### ISSUE TITLE
Error using webpack

### ISSUE THREAD

**Issue by jibon57** [NativeScript/template-drawer-navigation-ng#33]
Hi,

I am getting following error when I use webpack.

```
ERROR in ENOENT: no such file or directory, open 'D:\Others\Desktop\test\test\app\shared\my-drawer\my-drawer.component.android.css'

ERROR in ./main.aot.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in 'D:\Others\Desktop\test\test\app'
 @ ./main.aot.ts 5:29-62
```
How can I solve it?

Thanks

**Comment by lini** [comment]
The [nativescript-dev-webpack](https://github.com/NativeScript/nativescript-dev-webpack/) package is not fully compatible with SASS yet. Since we use SASS instead of CSS in the templates, you will get errors if you try to add it and build with webpack. There are a couple issues logged for this already and I hope that full support for SASS will come in a future release of nativescript-dev-webpack.

**Comment by SamuelM333** [comment]
Try doing a regular build with `tns build android` before running webpack. The regular build will generate the .css files if the webpack script doesn't.
