### ISSUE TITLE
webpack + template-drawer-navigation-ng = bugs

### ISSUE THREAD

**Issue by fant0m** [NativeScript/template-drawer-navigation-ng#42]
Hello,
I made a new application using this template but there are some bugs on android:
1. when I open the app on my phone (android 6.0.1.) sometimes there aren't any side drawer items (there's just header and blank space)
2. sometimes when the items do appear, they do not have correct styles http://prntscr.com/ge1hfr

p.s. app works correctly without webpack

**Comment by manoldonev** [comment]
Hello @fant0m,

The [nativescript-dev-webpack](https://github.com/NativeScript/nativescript-dev-webpack) package is not fully compatible with SASS yet. Since we use SASS instead of CSS in the templates, you will get errors if you try to add it and build with webpack. There are a couple issues logged for this already so hopefully full support for SASS will come in a future release of nativescript-dev-webpack.

**Comment by fant0m** [comment]
Hi @manoldonev, 
I'm actually not getting any errors during a build but thanks for info.

**Comment by manoldonev** [comment]
Yup, it's not just a matter of building it but with specific unsupported (or not properly supported) resource loaders as well.
