### ISSUE TITLE
Webpack: ListView GridLayouts Class Names Missing

### ISSUE THREAD

**Issue by jevenson** [NativeScript/template-drawer-navigation-ng#56]
See these issues:
[nativescript-dev-webpack#257](https://github.com/NativeScript/nativescript-dev-webpack/issues/257)
[nativescript-angular#984](https://github.com/NativeScript/nativescript-angular/issues/984)

The dynamic class name on the GridLayouts on the side drawer are failing when using Webpack to build your {N} app. I found that removing the `sidedrawer-list-item-{{item.name}}` from here
[my-drawer.component.html#L16](https://github.com/NativeScript/template-drawer-navigation-ng/blob/95855ef8097f35a4d568de9ad53d43167f5c096d/shared/my-drawer/my-drawer.component.html#L16) resolves the issue.

Not sure what is causing this, I would assume its some kind of parsing issue. Until the root cause is determined, the code should be updated to remove the `{{ }}` notation and use ngClass or some other alternative, to prevent others from having this issue.

I'll try to work on an alternative this weekend.

**Comment by MIYankov** [comment]
@jevenson Thank you for raising this issue. We were recently thinking about changing the idea of the code in the drawer since having this separator as a border top style is not the best idea from a semantic point of view. We will probably separate the items in two lists to show that you can have more than one list in there. Further, dynamically assigning class names to a list of items is a bit quirky.

That being said, this is an interesting issue. Only the classes that are together with the interpolated class name fail to apply. The other local css applies. My guess is that the angular webpack scopes the css class names by renaming them and it can't figure out the interpolated class names. We have to investigate further. I also tested it with ngClass and [ngClass]="{'sidedrawer-list-item': true, 'sidedrawer-list-item-settings': isSettings(item.name)}" works also fine.
